### ISSUE TITLE
How to disable weekend in calendar? 

### ISSUE THREAD

**Issue by mursyidah** [tizisdeepan/eventscalendar#1]
Disable weekend day in calendar

**Comment by tizisdeepan** [comment]
What do you mean by disabling weekend? Can you please explain? If its reasonable, I will make the required changes.

**Comment by mursyidah** [comment]
i mean is there a function to disable day in calendar? user can't click the day that are disable

**Comment by tizisdeepan** [comment]
Sure. Will make it possible in the next release.

**Comment by tizisdeepan** [comment]
@mursyidah I have implemented a simple disable feature for Events Calendar. Please use version 1.0.4 to get hold of the required methods.

You can now use,
``` kotlin
eventsCalendar.disableDate(calendar)
eventsCalendar.disableDayInWeek(Calendar.SATURDAY, Calendar.SUNDAY)
```
