### ISSUE TITLE
Perform Long Click On Date

### ISSUE THREAD

**Issue by riddhee** [tizisdeepan/eventscalendar#10]
Is there any method to perform long click on date view?

**Comment by tizisdeepan** [comment]
@riddhee Not right now. I will do the required changes for that and push it in the next update. Stay tuned!

**Comment by riddhee** [comment]
bt i need it urgently
can you guide me on that?

**Comment by tizisdeepan** [comment]
**[FIXED]** Use version **1.5.1** or above!
**USAGE**
``` Kotlin
class MainActivity : AppCompatActivity(), EventsCalendar.Callback {
    override fun onDayLongPressed(selectedDate: Calendar?) {
        Log.e("LONG CLICKED", EventsCalendarUtil.getDateString(selectedDate, EventsCalendarUtil.DD_MM_YYYY))
    }

    override fun onMonthChanged(monthStartDate: Calendar?) {
        Log.e("MON", "CHANGED")
    }

    override fun onDaySelected(selectedDate: Calendar?) {
        Log.e("CLICKED", EventsCalendarUtil.getDateString(selectedDate, EventsCalendarUtil.DD_MM_YYYY))
        selected.text = getDateString(selectedDate?.timeInMillis)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        ....
   }
}
```

The Callback to be implemented in Activity/ Fragment now has access to a new method called **onDayLongPressed** which is called when a date is long pressed on the Events Calendar.

Happy Coding!

**Comment by tizisdeepan** [comment]
@riddhee can you update on this? Have you tried it out?

**Comment by riddhee** [comment]
Thank you very much for the help

ya i tried bt i face one issue like when i long press on some date it should not be selected can you suggest me how to solve

**Comment by tizisdeepan** [comment]
@riddhee it is tricky. You work with this for now. I will work on it and update ASAP.

> I will remove selection property in long press by default. If you want the date to be selected, you can pass selectCurrentDate method inside Long Press delegate. 

Is this ok for you?

**Comment by riddhee** [comment]
yaa ,
Thank You

**Comment by tizisdeepan** [comment]
@riddhee I have tried overriding the gesture properties in the custom view. It seems, click action tends to happen mandatorily when long press action ends. We cannot override it to make it do otherwise. I can be of no help here. Sorry!
