### ISSUE TITLE
Remove last month and next month day display

### ISSUE THREAD

**Issue by Billylalalallaa** [tizisdeepan/eventscalendar#12]
can we remove last month and next month day display?
![device-2018-10-25-193738](https://user-images.githubusercontent.com/44467391/47497712-9533fa00-d88d-11e8-811c-f7c88718aee5.png)

**Comment by tizisdeepan** [comment]
If I remove those dates, the calendar's height won't be constant. Some months might have 4 rows and some might have 5, the scroll won't look good either. I can give an option to disable the visibility of the extra dates though. Will soon update on it.
