### ISSUE TITLE
How to reduce the font size of the calender dates?

### ISSUE THREAD

**Issue by bhoomit11** [tizisdeepan/eventscalendar#14]

**Comment by tizisdeepan** [comment]
It is not possible right now. I will update and release a new build with this feature included sometime soon!

**Comment by bhoomit11** [comment]
How to reduce the font size?
did you add a method for that?
if yes then please add in "Readme" 

Thank you.

**Comment by tizisdeepan** [comment]
Sure. Stay tuned for the next release, today.

**Comment by tizisdeepan** [comment]
Please check release 1.6.0
```
dependencies {
    implementation 'com.github.tizisdeepan:eventscalendar:1.6.0'
}
```
I have updated the README.
Happy Coding!

**Comment by bhoomit11** [comment]
> Please check release 1.6.1
> 
> ```
> dependencies {
>     implementation 'com.github.tizisdeepan:eventscalendar:1.6.1'
> }
> ```
> 
> I have updated the README.
> Happy Coding!

Thank you.
