### ISSUE TITLE
How to add events using array of string

### ISSUE THREAD

**Issue by zshadabm** [tizisdeepan/eventscalendar#15]
hiii, i like the way you design the calendar, we have a array of string containing dates. how to add in your calendar the array of strings.. appreciate your help in advance

**Comment by ziadagh** [comment]
Did you find a way to do this?

**Comment by tizisdeepan** [comment]
Do a for loop and pass the calendar instance to the addEvent method.
```
val c = Calendar.getInstance()
for(i in 0..3) {
   c.add(Calendar.DAY_OF_MONTH, i)
   eventsCalendar?.addEvent(c)
}
```
