### ISSUE TITLE
Can we Disable Multiple Date at once.

### ISSUE THREAD

**Issue by kamleshAvion** [tizisdeepan/eventscalendar#16]
We can select only **one** date using disableDate(), 
here last date which we pass is disable, but not the previous one.

**example:** 
 for (Calendar date :AVAILABLE_DATE_LIST) {
    eventsCalendar.disableDate(date);
}  
here only last date is disable not all date from list.

**Question** : How can we disable all the date from the list "AVAILABLE_DATE_LIST" ?

**Comment by tizisdeepan** [comment]
Not possible right now.
