### ISSUE TITLE
In fragment its not working properly 

### ISSUE THREAD

**Issue by DastanIqbal** [tizisdeepan/eventscalendar#21]
Seems like in fragment its not working properly, whenever I subtract year in calendar for DateRange its show unexpected result, I don't know why its shows 2039 or previous month July 2019

```
val start = DateTimeUtils.CalendarInstance()
start.add(Calendar.YEAR, -10)

val end = DateTimeUtils.CalendarInstance()
end.add(Calendar.YEAR, 20)

eventsCalendar.setMonthRange(start, end)
```
but its work in activity. I am using Jetpack Navigation component, and when calendar fragment is start fragment then its work, but when I put directions or navigate() to calendar fragment from other fragment then the behavior is unpredictable.

**Comment by DastanIqbal** [comment]
The solution I followed, I created setup method and copied `onAttachedWindow()` code and  deleted `onAttachedToWindow()` . and calling setup at the end of eventCalendar setting. 

       ```
        val start = Calendar.getInstance()
        start.add(Calendar.YEAR, -10)

        val end = Calendar.getInstance()
        end.add(Calendar.YEAR, 20)

        eventsCalendar.setCallback(this)
        eventsCalendar.setSelectionMode(eventsCalendar.MULTIPLE_SELECTION)
        eventsCalendar.setToday(today)
        eventsCalendar.setMonthRange(start, end)
        eventsCalendar.setWeekStartDay(Calendar.SUNDAY, false)
        eventsCalendar.setCurrentSelectedDate(today)
        eventsCalendar.setDatesTypeface(App.poppinsTypeface!!)
        eventsCalendar.setMonthTitleTypeface(App.poppinsBoldTypeface!!)
        eventsCalendar.setWeekHeaderTypeface(App.poppinsTypeface!!)

        eventsCalendar.setup()
```
so far its working, let me know if you have any better fix.

**Comment by DastanIqbal** [comment]
The solution I followed, I created `setup()` method and copied `onAttachedWindow()` code and  deleted `onAttachedToWindow()`  or can say renamed. and calling setup at the end of eventCalendar setting. 

       ```
        val start = Calendar.getInstance()
        start.add(Calendar.YEAR, -10)

        val end = Calendar.getInstance()
        end.add(Calendar.YEAR, 20)

        eventsCalendar.setCallback(this)
        eventsCalendar.setSelectionMode(eventsCalendar.MULTIPLE_SELECTION)
        eventsCalendar.setToday(today)
        eventsCalendar.setMonthRange(start, end)
        eventsCalendar.setWeekStartDay(Calendar.SUNDAY, false)
        eventsCalendar.setCurrentSelectedDate(today)
        eventsCalendar.setDatesTypeface(App.poppinsTypeface!!)
        eventsCalendar.setMonthTitleTypeface(App.poppinsBoldTypeface!!)
        eventsCalendar.setWeekHeaderTypeface(App.poppinsTypeface!!)

        eventsCalendar.setup()
```
so far its working, let me know if any better fix.

**Comment by tizisdeepan** [comment]
onAttachedToWindow() is the first method that will be called when initialising a View in android. It is not bundled with either Activity or Fragment but totally involved in the view's lifecycle. I wonder why your solution worked. But it seems to have fixed the problem now with an extra line of code. I will try to work on simplifying things related to this issue. Do give me a pull request and I will merge your code for now until I work on a fix.

**Comment by DastanIqbal** [comment]
Ya I found other problems also when I show fragment 1st time then its select current date, its fine but after open fragment again, and select any date then date selector run for few seconds in grid view, I debug and I found `setCurrentSelectedDate(cal)`  method calling in loop, 

To fix this I removed post{} and made `mCalendarMonthsAdapter` nullable , (removed lateinit), and calling `setCurrentSelectedDate(today)` in post. 
```
eventsCalendar.post {
            eventsCalendar.setCurrentSelectedDate(today)
}
```

No doubt your library is so easy to implement, I tried other libraries they all are very verbose. Thanks.

**Comment by tizisdeepan** [comment]
Thanks for taking interest in the library. When I developed it, jetpack components weren't a thing, so I ignored it. I really appreciate your work and I will work to improve the library. I am pushing a release today for setting font sizes to each component in the library, do check it out. And, feel free to let me know, if there are other improvements which can be done. I made this library because, as we all know, android's native Calendar component is bad and is void of many good requested features, so I guess EventsCalendar would live long, until Google releases a good Calendar component. Keep up the good work and keep me posted on issues that you may face in the future.

Thanks again and happy coding!

**Comment by tizisdeepan** [comment]
And I do appreciate the builder pattern. Good one!
