### ISSUE TITLE
Show selected dates

### ISSUE THREAD

**Issue by gaganAriel** [tizisdeepan/EventsCalendar#24]
Can i show multiple dates selected like i opened calendar class and i want to show multiple dates selected and also on click that dates i want to deselect that dates.

Thank you

**Comment by tizisdeepan** [comment]
You can do that by changing the selection mode to MULTIPLE_SELECTION.
`eventsCalendar.setSelectionMode(eventsCalendar.MULTIPLE_SELECTION)`

**Comment by gaganAriel** [comment]
that will for selection but my question is that when i opened calendar class there should be default some dates are selected.

**Comment by tizisdeepan** [comment]
Use the below line of code to select a date programatically
`eventsCalendar.setCurrentSelectedDate(calendarObject)`
