### ISSUE TITLE
SINGLE_SELECTION' has private access in 'com.events.calendar.views.EventsCalendar

### ISSUE THREAD

**Issue by deLTreeTech** [tizisdeepan/EventsCalendar#25]
Set SINGLE SELECTION shows 'SINGLE_SELECTION' has private access in 'com.events.calendar.views.EventsCalendar' as error. Is there anything wrong with the code below.

Also, if I remove this line ' .setSelectionMode(EventsCalendar.SINGLE_SELECTION)', the '.addEvent(cal)' prevents the Calender from building. 

Can you please explain this

eventsCalendar.setCallback(this)
                .setToday(Calendar.getInstance())
                .setMonthRange(minMonth, maxMonth)
                .setCurrentSelectedDate(Calendar.getInstance())
                .setSelectionMode(EventsCalendar.SINGLE_SELECTION)
                .addEvent(cal)
                .build();

**Comment by tizisdeepan** [comment]
use the latest version 1.6.1 to avoid this issue. SINGLE_SELECTION is not private and can be set as the selection mode.
