### ISSUE TITLE
Unable to Add Events

### ISSUE THREAD

**Issue by nicemak** [tizisdeepan/EventsCalendar#27]
**Describe the bug**
Adding events not working. eventsCalendar.getDotsForMonth(c) return null

**To Reproduce**
`val c = Calendar.getInstance()
c.add(Calendar.DAY_OF_MONTH, 3)
eventsCalendar.addEvent(c)`

**Expected behavior**
show event on calender

**Comment by innoflash** [comment]
@nicemak have you found a solution to this?

**Comment by nicemak** [comment]
@innoflash i found this library https://github.com/kizitonwose/CalendarView, it has many options to customize

**Comment by innoflash** [comment]
@nicemak thanks mate, will check it out
