### ISSUE TITLE
Single selection bug

### ISSUE THREAD

**Issue by kelvinkioko** [tizisdeepan/EventsCalendar#31]
When on single selection the selection does not highlight  automatically

**To Reproduce**
1. eventsCalendar.setSelectionMode(eventsCalendar.SINGLE_SELECTION)
2. Run the app and select a date

**Expected behavior**
Ideally, the selected date should be highlighted automatically.

**Additional context**
I went through the EventsCalendar.kt and on 'setCurrentSelectedDate' function the 'SINGLE_SELECTION' option is missing the reset() and refreshTodayDate() functions

**Comment by kelvinkioko** [comment]
Adding those two functions fixed the issue on my end

**Comment by DevLuke67** [comment]
Yes, thanks

**Comment by upendracraftsilicon** [comment]
Thanks. This should be added to this.
